[package]
name = "CommitmentKZG"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "*"
ark-poly = "*"
ark-bls12-381 = "*"
ark-std = "*"
ark-ec = "*"
rand =  "*"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
